name: Crystal Specs
on: [push, pull_request]
jobs:
  debug_status:
    name: Debug Status
    runs-on: ubuntu-20.04	
    env:
      skip_debug: ${{secrets.SKIP_DEBUG}}
      release_debug: ${{secrets.RELEASE_DEBUG}}
      build_debug: ${{secrets.BUILD_DEBUG}}
    steps:
    - name: Create Debug Files
      run: |
        touch skip_debug
        touch release_debug
        touch build_debug
        if [[ "$skip_debug" == 'true' ]]; then
           echo 'true' > skip_debug
        fi
        if [[ "$release_debug" == 'true' ]]; then
           echo 'true' > release_debug
        fi
        if [[ "$build_debug" == 'true' ]]; then
           echo 'true' > build_debug
        fi
    - name: upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: debug_status
        path: |
          skip_debug
          release_debug
          build_debug
  debug_output:
    name: Debug Outputs
    needs: [debug_status]
    runs-on: ubuntu-20.04	
    outputs:
      skip-debug: ${{ steps.skip-debug.outputs.debug }}
      release-debug: ${{ steps.release-debug.outputs.debug }}
      build-debug: ${{ steps.build-debug.outputs.debug }}
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: debug_status
    - id: skip-debug
      run: |
        if grep -q 'true' "./skip_debug"; then 
          echo "::set-output name=debug::true"
        fi
    - id: release-debug
      run: |
        if grep -q 'true' "./release_debug"; then 
          echo "::set-output name=debug::true"
        fi
    - id: build-debug
      run: |
        if grep -q 'true' "./build_debug"; then 
          echo "::set-output name=debug::true"
        fi
  tests:
    name: Fetch Matrix Tests
    runs-on: ubuntu-20.04	
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - id: set-matrix
      run: |
        JSON="{\"include\":["
        TEST_LIST=$(for i in $(find spec -name '*_spec.cr')
        do
            if ! [ "$i" == "spec/workload/cpu_hog_spec.cr" ]; then
                 echo "{\"spec\":\"$i\"}," | tr -d '\n'
            fi
        done)
        TEST_LIST="${TEST_LIST%?}"
        JSON="$JSON$TEST_LIST"
        JSON="$JSON]}"
        echo "::set-output name=matrix::$JSON"
  skip:
    name: Skip Build
    runs-on: ubuntu-20.04	
    needs: [debug_output]
    outputs:
      skip: ${{ steps.skip.outputs.skip }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: mxschmitt/action-tmate@v3
      if: needs.debug_output.outputs.skip-debug == 'true'
    - id: skip
      run: |
        echo "::set-output name=skip::$(.github/workflows/skip.sh)"

  spec:
    name: Crystal Specs
    needs: [tests, skip]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.tests.outputs.matrix)}}
    if: needs.skip.outputs.skip == 'false'
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install Clusterctl
      run: |
        curl -L https://github.com/kubernetes-sigs/cluster-api/releases/download/v0.3.10/clusterctl-linux-amd64 -o clusterctl
        chmod +x ./clusterctl
        sudo mv ./clusterctl /usr/local/bin/clusterctl
    - name: Install Crystal
      env:
        CRYSTAL_VERSION: 0.35.1
        CRYSTAL_URL: https://github.com/crystal-lang/crystal/releases/download
      run: |
        wget -O crystal.deb "$CRYSTAL_URL/$CRYSTAL_VERSION/crystal_$CRYSTAL_VERSION-1_amd64.deb" --progress=dot:giga; 
        sudo apt install -y --no-install-recommends \
        git \
        libssl-dev \
        libxml2-dev \
        libyaml-dev \
        libgmp-dev \
        libz-dev \
        ./crystal.deb \
        && sudo rm -rf /var/lib/apt/lists/*
    - name: Create Kind Cluster 
      run: |
        cat << EOF > /tmp/cluster.yml
        kind: Cluster
        apiVersion: kind.x-k8s.io/v1alpha4
        containerdConfigPatches:
        - |-
          [plugins."io.containerd.grpc.v1.cri".registry.mirrors."registry:5000"]
            endpoint = ["http://localhost:5000"]
        EOF
        kind create cluster --config=/tmp/cluster.yml
        kubectl get nodes 
    - name: Setup CNF-Conformance
      run: |
        helm repo add stable https://cncf.gitlab.io/stable
        git fetch --all --tags --force
        shards install  
        crystal src/cnf-conformance.cr setup
    - name: Run Crystal Spec
      env:
        GITHUB_USER: ${{ secrets.GH_USER }}
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        PROTECTED_DOCKERHUB_EMAIL: ${{ secrets.PROTECTED_DOCKERHUB_EMAIL }}
        PROTECTED_DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        PROTECTED_DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      run: |
        LOG_LEVEL=info crystal spec --warnings none ${{ matrix.spec }} -v

  build:
    name: Build Release
    needs: [skip, debug_output]
    runs-on: ubuntu-latest
    if: needs.skip.outputs.skip == 'false'
    steps: 
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: mxschmitt/action-tmate@v3
      if: needs.debug_output.outputs.build-debug == 'true'
    - name: Install Crystal
      env:
        CRYSTAL_VERSION: 0.35.1
        CRYSTAL_URL: https://github.com/crystal-lang/crystal/releases/download
      run: |
        wget -O crystal.deb "$CRYSTAL_URL/$CRYSTAL_VERSION/crystal_$CRYSTAL_VERSION-1_amd64.deb" --progress=dot:giga; 
        sudo apt install -y --no-install-recommends \
        git \
        libssl-dev \
        libxml2-dev \
        libyaml-dev \
        libgmp-dev \
        libz-dev \
        ./crystal.deb \
        && sudo rm -rf /var/lib/apt/lists/*
    - name: Build Release
      run: |
        shards install
        docker pull conformance/crystal:0.35.1
        docker run --rm -v $PWD:/workspace -w /workspace conformance/crystal:0.35.1-llvm10-grep crystal build --warnings none src/cnf-conformance.cr --release --static --link-flags '-lxml2 -llzma'
    - name: upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: release
        path: cnf-conformance
  test_binary_no_source:
    name: Test Binary Without Source
    needs: [spec, build, debug_output]
    runs-on: ubuntu-latest
    steps: 
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: release
    - uses: mxschmitt/action-tmate@v3
      if: needs.debug_output.outputs.release-debug == 'true'
    - name: Run Test Suite without source
      run: |
        chmod +x ./cnf-conformance
        cnf-conformance setup
        wget -O cnf-conformance.yml https://raw.githubusercontent.com/cncf/cnf-conformance/master/example-cnfs/coredns/cnf-conformance.yml
        cnf-conformance cnf_setup cnf-config=./cnf-conformance.yml
        cnf-conformance workload
  release:
    name: Publish Release
    needs: [spec, build, debug_output]
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: release
    - uses: mxschmitt/action-tmate@v3
      if: needs.debug_output.outputs.release-debug == 'true'
    - name: Make release executable
      run: chmod +x ./cnf-conformance
    - name: Publish Release
      env:
        GITHUB_USER: ${{ secrets.GH_USER }}
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        if [ -z "${GITHUB_USER+x}" ] || [ -z "${GITHUB_TOKEN+x}" ]; then
          exit 0
        else
          ./cnf-conformance upsert_release
        fi

